[package]
name = "armadillo"
description = "A simple Rust library to effectively encrypt and decrypt data. Meant to take the thinking away from the security."
version = "0.0.1"
edition = "2021"

license = "MIT"

[dependencies]
num-bigint = "0.4.5"

[dev-dependencies]
hex-literal = "0.4.1"
